language: android
dist: trusty
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
  components:
    - tools
    - build-tools-30.0.3
    - android-30
    - android-23
    - extra