[versions]

# plugins
android-gradle-plugin = "7.4.0"
jetbrains-kotlin-android = "1.7.10"
hilt-android = "2.42"

# app
activity = "1.6.1"
accompanist = "0.23.1"
coil = "2.2.2"
compose = "1.3.1"
compose-ui-tooling = "1.3.3"
coroutines = "1.6.4"
hilt = "2.44.2"
hilt-navigation = "1.0.0"
hilt-compiler = "2.42"
ktx = "1.9.0"
kotlinx-coroutines-core = "1.6.4"
lifecycle = "2.5.1"
lifecycle-extensions = "2.2.0"
navigation = "2.5.3"
okhttp = "4.10.0"
retrofit = "2.9.0"
room = "2.5.1"

# tests
androidx-test-ui = "1.3.3"
androidx-test-core = "2.2.0"
archunit = "1.0.1"
core-testing = "2.1.0"
coroutines-test = "1.6.4"
junit = "1.1.5"
mockk = "1.13.3"
mockito-core = "5.0.0"
mockwebserver = "4.9.2"
runner = "1.5.2"
truth = "1.1.3"
turbine = "0.12.1"

[libraries]

# app
accompanist                 = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
activity-ktx                = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
activity-compose            = { module = "androidx.activity:activity-compose", version.ref = "activity" }
coil                        = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-material            = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui                  = { module = "androidx.compose.ui:ui", version.ref = "compose"}
compose-ui-tooling          = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui-tooling" }
compose-ui-tooling-preview  = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
core-ktx                    = { module = "androidx.core:core-ktx", version.ref = "ktx" }
coroutines                  = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
navigation                  = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
hilt-android                = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler               = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-compiler" }
hilt-navigation-compose     = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation" }
lifecycle-extensions        = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-runtime-ktx       = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx     = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
okhttp3                     = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor         = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit2                   = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson              = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
room-ktx                    = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime                = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler               = { module = "androidx.room:room-compiler", version.ref = "room" }

# tests
core-testing                = { module = "androidx.arch.core:core-testing", version.ref = "androidx-test-core" }
compose-ui-test-junit4      = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-test-ui" }
compose-ui-test-manifest    = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-test-ui" }
coroutines-test             = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }
junit                       = { module = "androidx.test.ext:junit", version.ref = "junit" }
mockk                       = { module = "io.mockk:mockk", version.ref = "mockk" }
mockito                     = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockwebserver               = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
runner                      = { module = "androidx.test:runner", version.ref = "runner" }
tngtech-archunit            = { module = "com.tngtech.archunit:archunit", version.ref = "archunit" }
turbine                     = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
truth                       = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]

android-application         = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library             = { id = "com.android.library", version.ref = "android-gradle-plugin" }
jetbrains-kotlin-android    = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrains-kotlin-android" }
hilt-android                = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }

[bundles]

#common-test = [
#    "test-junit",
#    "test-kotlin",
#    "test-kotlin-coroutines",
#    "test-mockk",
#    "test-turbine"
#]
#common-android-test = [
#    "test-android-compose",
#    "test-android-hilt",
#    "test-android-runner"
#]

