name: 'Checkout code & Set up Java 17'
description: 'Checkout code and Set up Java 17'
runs:
  using: 'composite'
  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
