name: 'Set up Java 17 & Access Api key'
description: 'Set up Java 17 & Access Api key'
runs:
  using: 'composite'
  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v4 # https://github.com/marketplace/actions/setup-java-jdk
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Access THE_GUARDIAN_API_KEY
      run: echo THE_GUARDIAN_API_KEY=\"$THE_GUARDIAN_API_KEY\" > ./local.properties
      shell: bash
