name: android CI

# when this workflow should be executed.
on:
  push:
    branches:
      - main
      - develop
      - 'feat/**'
      - 'release/**'
    tags:
      - 'v*'
  pull_request:
    types:
      - opened
      - reopened
  schedule:
    - cron: '0 11 * * 1'
  # this event makes sure that the user can manually trigger this workflow.
  workflow_dispatch:

env:
  APP_NAME: the-guardian
  THE_GUARDIAN_API_KEY: ${{ secrets.THE_GUARDIAN_API_KEY }}
  RETENTION_DAYS: 10

jobs:

  android-workflow:

    # runner on which the job will execute different steps (environment).
    runs-on: ubuntu-latest

    env:
      RUN_NUMBER: ${{github.run_number}}

    steps:

      # run defines the command that should be executed in the command line.
      - name: Starting...
        run: echo "Job automatically triggered by a ${{ github.event_name }} event on branch ${{ github.ref }}"

      # step name
      - name: Get the code
        # uses is a keyword to use an action.
        uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout

      - name: set up JDK 17
        uses: actions/setup-java@v4 # https://github.com/marketplace/actions/setup-java-jdk
        # with is a keyword to take various keys that configure the action.
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Access THE_GUARDIAN_API_KEY
        run: echo THE_GUARDIAN_API_KEY=\"$THE_GUARDIAN_API_KEY\" > ./local.properties

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble Prod debug build
        run: ./gradlew assembleProdDebug

      - name: Assemble Mock debug build
        run: ./gradlew assembleMockDebug

      - name: Run unit tests
        # assign unique id to the step to reference it.
        id: run-unit-tests
        run: ./gradlew testProdDebugUnitTest

      - name: Upload unit tests artifact
        # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
        # https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
        if: failure() && steps.run-unit-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4 # https://github.com/marketplace/actions/upload-a-build-artifact
        with:
          name: unit-tests-report # job artifact name
          path: app/build/reports/tests/testProdDebugUnitTest/index.html # job artifact to upload
          retention-days: ${{ env.RETENTION_DAYS }}

      # https://github.com/marketplace/actions/authenticate-to-google-cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Firebase App Distribution
        # the job should continue execution even if that step fails.
        continue-on-error: true
        run: ./gradlew appDistributionUploadProdDebug --releaseNotesFile=release_notes.txt --groups=testers

      - name: Upload .apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-debug-${{ env.RUN_NUMBER }}
          path: app/build/outputs/apk/prod/debug/app-prod-debug.apk
          retention-days: ${{ env.RETENTION_DAYS }}

  analysis-workflow:

    runs-on: ubuntu-latest

    steps:

      - name: Get the code
        uses: actions/checkout@v4

      - name: Checkout code & Set up Java 17
        uses: ./.github/actions/common

      - name: Run code analysis (Lint)
        run: ./gradlew lintProdDebug

      - name: Upload code analysis artifact
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: app/build/reports/lint-results-prodDebug.html
          retention-days: ${{ env.RETENTION_DAYS }}


