name: android CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

jobs:

  android-workflow:

    runs-on: ubuntu-latest

    env:
      APP_NAME: the-guardian
      RUN_NUMBER: ${{github.run_number}}
      THE_GUARDIAN_API_KEY: ${{ secrets.THE_GUARDIAN_API_KEY }}
      RETENTION_DAYS: 10
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    steps:

      - run: echo "Job automatically triggered by a ${{ github.event_name }} event on branch ${{ github.ref }}"

      - name: Checkout the code
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Access THE_GUARDIAN_API_KEY
        run: echo THE_GUARDIAN_API_KEY=\"$THE_GUARDIAN_API_KEY\" > ./local.properties

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble Prod debug build
        run: ./gradlew assembleProdDebug

      - name: Distribute
        run: ./gradlew appDistributionUploadProdDebug

#      - name: Assemble Mock debug build
#        run: ./gradlew assembleMockDebug

#      - name: Run unit tests
#        run: ./gradlew testProdDebugUnitTest

#      - name: Upload unit tests results
#        uses: actions/upload-artifact@v2
#        with:
#          name: unit-tests-results
#          path: app/build/reports/tests/testProdDebugUnitTest/index.html
#          retention-days: ${{ env.RETENTION_DAYS }}

#      - name: Upload .apk
#        uses: actions/upload-artifact@v2
#        with:
#          name: ${{ env.APP_NAME }}-debug-${{ env.RUN_NUMBER }}
#          path: app/build/outputs/apk/prod/debug/app-prod-debug.apk
#          retention-days: ${{ env.RETENTION_DAYS }}

#      - name: Run code analysis (Lint)
#        run: ./gradlew lintProdDebug

#      - name: Upload code analysis results
#        uses: actions/upload-artifact@v2
#        with:
#          name: lint-results
#          path: app/build/reports/lint-results-prodDebug.html
#          retention-days: ${{ env.RETENTION_DAYS }}