name: android CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  github-action:

    runs-on: ubuntu-latest

    env:
      APP_NAME: the-guardian
      RUN_NUMBER: ${{ github.run_number}}
      BUILD_TYPE: Prod

    steps:
      - run: echo "Job automatically triggered by a ${{ github.event_name }} event on branch ${{ github.ref }}"

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Access THE_GUARDIAN_API_KEY
        env:
          THE_GUARDIAN_API_KEY: ${{ secrets.THE_GUARDIAN_API_KEY }}
        run: echo THE_GUARDIAN_API_KEY=\"$THE_GUARDIAN_API_KEY\" > ./local.properties

      - name: starts a ${BUILD_TYPE} debug build
        run: ./gradlew assemble${BUILD_TYPE}Debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}-debug-${{ env.RUN_NUMBER }}
          path: app/build/outputs/apk/${BUILD_TYPE}/debug/app-prod-debug.apk

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        id: step_one
        uses: actions/checkout@v2

      - name: set up JDK 17
        id: step_two
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

#      - name: Run connected tests
#        uses: ReactiveCircus/android-emulator-runner@v2
#        with:
#          api-level: 30
#          target: google_apis
#          arch: x86_64
#          script: ./gradlew connectedCheck

      - name: Access THE_GUARDIAN_API_KEY
        env:
          THE_GUARDIAN_API_KEY: ${{ secrets.THE_GUARDIAN_API_KEY }}
        run: echo THE_GUARDIAN_API_KEY=\"$THE_GUARDIAN_API_KEY\" > ./local.properties

      - name: Run unit test
        run: ./gradlew testProdDebugUnitTest

      - name: Archive tests results
        uses: actions/upload-artifact@v2
        with:
          name: tests-report
          path: app/build/reports/tests/testProdDebugUnitTest/index.html

  code-analysis-reports :
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 17
        id: step_two
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Access THE_GUARDIAN_API_KEY
        env:
          THE_GUARDIAN_API_KEY: ${{ secrets.THE_GUARDIAN_API_KEY }}
        run: echo THE_GUARDIAN_API_KEY=\"$THE_GUARDIAN_API_KEY\" > ./local.properties

      - name: Check Lint
        run: ./gradlew lintProdDebug

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: app/build/reports/lint-results-prodDebug.html
