name: Common steps

on:
  workflow_run:
    workflows: ["android-workflow", "analysis-workflow"]
    types:
      - completed

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
